services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "${VITE_API_URL}"
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./server/logs:/usr/src/app/logs
    networks:
      - app-network
    environment:
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      PORT: "3000"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    expose:
      - "5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
