version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      CLIENT_URL: "${CLIENT_URL}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
      PORT: "${PORT}"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
